

export const MENUS_BY_RESTAURANT = {
  'sakura-ramen': [
    {
      id: 'classic-ramen',
      name: 'Classic  Ramen',
      description: '18-hour cooked broth, hand-pulled noodles, chashu, soft-boiled egg.',
      category: 'NonVeg Ramen',
      price: 450,
      dietType: 'non-veg',
      image: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?q=80&w=600&auto=format&fit=crop',
    },
    {
    id: 'chicken',
    name: 'Fried Chicken Bites',
    description: 'Japanese-style fried chicken bites with a squeeze of lemon.',
    category: 'Sides',
    price: 260,
    dietType: 'non-veg',
    image: 'https://plus.unsplash.com/premium_photo-1669742928112-19364a33b530?w=600&auto=format&fit=crop',
  },
   {
    id: 'seaweed-salad',
    name: 'Seaweed Salad',
    description: 'Chilled wakame salad with sesame and a light rice-vinegar dressing.',
    category: 'Sides',
    price: 180,
    dietType: 'veg',
    image: 'https://plus.unsplash.com/premium_photo-1700840833134-3f6ad783f8bb?w=600&auto=format&fit=crop',
  },
  {
    id: 'veggie-dumplings',
    name: 'Veggie Dumplings',
    description: 'Pan-fried dumplings filled with cabbage, mushroom, and chives.',
    category: 'Sides',
    price: 220,
    dietType: 'veg',
    image: 'https://plus.unsplash.com/premium_photo-1700746098867-29b475283b51?w=600&auto=format&fit=crop',
  },
    {
      id: 'veggie-ramen',
      name: 'Garden Vegetable Ramen',
      description: ' tofu, bok choy, corn, mushrooms.',
      category: ' Veg Ramen',
      price: 400,
      dietType: 'veg',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=600&auto=format&fit=crop',
    },
    {
    id: 'chicken-ramen',
    name: 'Chicken Ramen',
    description: 'Soy-flavored chicken broth topped with grilled chicken and soft egg.',
    category: 'NonVeg Ramen',
    price: 390,
    dietType: 'non-veg',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=600&auto=format&fit=crop',
  },
    {
      id: 'gyoza',
      name: 'Pan-Fried Pork Gyoza',
      description: 'Six pieces, crispy bottoms, served with ponzu dipping sauce.',
      category: 'Starters',
      price: 250,
      dietType: 'non-veg',
      image: 'https://images.unsplash.com/photo-1625938144755-652e08e359b7?q=80&w=600&auto=format&fit=crop',
    },
  ],
  'taco-house': [
    {
      id: 'al-pastor-taco',
      name: 'Al Pastor Tacos (3pc)',
      description: 'Slow-roasted pork, pineapple, onion, cilantro on corn tortillas.',
      category: 'Tacos',
      price: 280,
      dietType: 'non-veg',
      image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?q=80&w=600&auto=format&fit=crop',
    },
    {
      id: 'guac-chips',
      name: 'Guacamole & Chips',
      description: 'Fresh-mashed avocado, lime, cilantro, house-fried chips.',
      category: 'Starters',
      price: 220,
      dietType: 'veg',
      image: 'https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?q=80&w=600&auto=format&fit=crop',
    },
  ],
  'green-basil': [
    {
      id: 'green-curry',
      name: 'Green Curry',
      description: 'Coconut milk, Thai basil, bamboo shoots, choice of protein.',
      category: 'Curries',
      price: 380,
      dietType: 'veg',
      image: 'https://plus.unsplash.com/premium_photo-1713089366140-814130d69933?w=600&auto=format&fit=crop',
    },
    {
    id: 'spring-rolls',
    name: 'Fresh Spring Rolls',
    description: 'Rice paper rolls packed with herbs, and crisp vegetables, served with peanut dipping sauce.',
    category: 'Starters',
    dietType: 'veg',
    price: 260,
    image: 'https://images.unsplash.com/photo-1606525437679-037aca74a3e9?w=600&auto=format&fit=crop',
  },
  {
    id: 'chicken',
    name: 'Chicken Satay',
    description: 'Grilled skewers marinated in coconut milk and turmeric, served with a rich peanut sauce.',
    category: 'Starters',
    dietType: 'non-veg',
    price: 340,
    image: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'prawn-curry',
    name: 'Red Curry with Prawns',
    description: 'Bold and spicy, with red curry paste, coconut milk, bell peppers, and fresh prawns.',
    category: 'Curries',
    dietType: 'non-veg',
    price: 520,
    image: 'https://images.unsplash.com/photo-1598635976790-5d73e627643a?w=600&auto=format&fit=crop',
  },
  {
    id: 'vegetable-curry',
    name: 'Massaman Vegetable Curry',
    description: 'A mild, peanut-based curry with potatoes, carrots, and tofu, slow-cooked with warm spices.',
    category: 'Curries',
    dietType: 'veg',
    price: 420,
    image: 'https://images.unsplash.com/photo-1720949579179-b4d04403f548?w=600&auto=format&fit=crop',
  },
   {
    id: 'chicken-curry',
    name: 'Green Curry with Chicken',
    description: 'Simmered in coconut milk with Thai basil, bamboo shoots, and green chilies. Signature dish of the house.',
    category: 'Curries',
    dietType: 'non-veg',
    price: 480,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'thai-fried-rice',
    name: 'Thai Fried Rice',
    description: 'Jasmine rice wok-tossed with egg, onions, and your choice of chicken, shrimp, or vegetables.',
    category: 'Rice',
    dietType: 'both',
    price: 340,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=600&auto=format&fit=crop',
  },
  {
       id: 'pineapple-fried-rice',
    name: 'Pineapple Fried Rice',
    description: 'Fried rice with pineapple chunks, cashews, raisins, and curry powder, served in a pineapple shell.',
    category: 'Rice',
    dietType: 'veg',
    price: 400,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sticky-rice',
    name: 'Mango Sticky Rice',
    description: 'Sweet coconut sticky rice served with fresh ripe mango slices and a drizzle of coconut cream.',
    category: 'Desserts',
    dietType: 'veg',
    price: 280,
    image: 'https://images.unsplash.com/photo-1711161988375-da7eff032e45?w=600&auto=format&fit=crop',
  },
  {
    id: 'iced-tea',
    name: 'Thai Iced Tea',
    description: 'Strong brewed black tea sweetened and served over ice with a splash of condensed milk.',
    category: 'Drinks',
    dietType: 'veg',
    price: 180,
    image: 'https://plus.unsplash.com/premium_photo-1726866175183-7fe0f6f9746f?w=600&auto=format&fit=crop',
  },
  ],
  'the-square': [
    {
      id: 'margherita-pizza',
      name: 'Margherita Pizza',
      description: 'Wood-fired, San Marzano tomato, fresh mozzarella, basil.',
      category: 'Pizza',
      price: 420,
      dietType: 'veg',
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=600&auto=format&fit=crop',
    },
    {
    id: 'pizza-02',
    name: 'Pepperoni',
    description: 'Loaded with spicy pepperoni slices and a generous layer of melted mozzarella.',
    category: 'Classic Pizzas',
    dietType: 'non-veg',
    price: 520,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=600&auto=format&fit=crop',
  },
   {
    id: 'pizza-05',
    name: 'BBQ Chicken',
    description: 'Grilled chicken, red onions, and smoky BBQ sauce topped with mozzarella and cilantro.',
    category: 'Specialty Pizzas',
    dietType: 'non-veg',
    price: 580,
    image: 'https://images.unsplash.com/photo-1586058584825-c1e87ed735b4?w=600&auto=format&fit=crop',
  },
  {
    id: 'pizza-06',
    name: 'Farmhouse',
    description: 'Loaded with bell peppers, onions, mushrooms, sweet corn, and tomatoes.',
    category: 'Specialty Pizzas',
    dietType: 'veg',
    price: 480,
    image: 'https://images.unsplash.com/photo-1717883235373-ef10b2a745a3?w=600&auto=format&fit=crop',
  },
  {
    id: 'pizza-07',
    name: 'Meat Lovers',
    description: 'A hearty mix of pepperoni, sausage, ham, and bacon on a classic tomato base.',
    category: 'Specialty Pizzas',
    dietType: 'non-veg',
    price: 620,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=600&auto=format&fit=crop',
  },
   {
    id: 'pizza-10',
    name: 'Garlic Bread',
    description: 'Freshly baked bread brushed with garlic butter and herbs, served warm.',
    category: 'Starters',
    dietType: 'veg',
    price: 220,
    image: 'https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=600&auto=format&fit=crop',
  },
  {
    id: 'pizza-11',
    name: 'Cheesy Garlic Breadsticks',
    description: 'Soft breadsticks topped with melted mozzarella and garlic herb butter.',
    category: 'Starters',
    dietType: 'veg',
    price: 280,
    image: 'https://images.unsplash.com/photo-1736589771973-6ffe71a6baec?w=600&auto=format&fit=crop',
  },
  {
    id: 'pizza-13',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce, parmesan shavings, croutons, and creamy Caesar dressing.',
    category: 'Salads',
    dietType: 'veg',
    price: 320,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'pizza-15',
    name: 'Chicken Alfredo Pasta',
    description: 'Fettuccine tossed in a creamy parmesan Alfredo sauce with grilled chicken.',
    category: 'Pasta',
    dietType: 'non-veg',
    price: 460,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'pizza-16',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
    category: 'Desserts',
    dietType: 'veg',
    price: 280,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=600&auto=format&fit=crop',
  },
  ],
  'daily-sushi': [
    {
      id: 'salmon-nigiri',
      name: 'Salmon Nigiri (2pc)',
      description: 'Fresh salmon over seasoned sushi rice.',
      category: 'Nigiri',
      price: 320,
      dietType: 'non-veg',
      image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?q=80&w=600&auto=format&fit=crop',
    },
  ],
  'angan-sweets': [
    
     {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    description: 'Soft milk-solid dumplings soaked in rose-cardamom sugar syrup.',
    category: 'Sweets',
    price: 180,
    dietType: 'veg',
    image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_600/ed75842c2f1eda868907463afd5d7a95',
  },
 {
  id: 'rasgulla',
  name: 'Rasgulla',
  description: 'Spongy chenna balls in light, fragrant sugar syrup.',
  category: 'Sweets',
  price: 170,
  dietType: 'veg',
  image: 'https://media.istockphoto.com/id/1283542929/photo/indian-rasgulla-or-dry-rosogulla-dessert-sweet-served-in-a-bowl.jpg?s=2048x2048&w=is&k=20&c=7FDXpOOYweN0ER0F-AccWLeuBTQK3oH32OH4fZ06Pyk=',
},
  {
    id: 'jalebi',
    name: 'Jalebi',
    description: 'Crisp, syrup-soaked spirals, best served warm.',
    category: 'Sweets',
    price: 160,
    dietType: 'veg',
    image: 'https://media.istockphoto.com/id/1159362325/photo/bread-pakora.jpg?s=2048x2048&w=is&k=20&c=byHZdxqMnk7IzCEmFWXVCMJtB0UpACmN9y5z6glcm_0=',
  },
  {
    id: 'kaju-katli',
    name: 'Kaju Katli',
    description: 'Cashew-based sweet, silver leaf topping.',
    category: 'Sweets',
    price: 200,
    dietType: 'veg',
    image: 'https://images.unsplash.com/photo-1708782343574-b9d0dc6dd112?q=80&w=880&auto=format&fit=crop',
  },
  {
    id: 'motichoor-laddu',
    name: 'Motichoor Laddu',
    description: 'Tiny fried gram-flour pearls bound with ghee and sugar syrup.',
    category: 'Laddus',
    price: 220,
    dietType: 'veg',
    image: 'https://images.unsplash.com/photo-1635952346904-95f2ccfcd029?q=80&w=687&auto=format&fit=crop',
  },
  {
    id: 'besan-laddu',
    name: 'Besan Laddu',
    description: 'Roasted gram-flour laddus rich with ghee and cardamom.',
    category: 'Laddus',
    price: 250,
    dietType: 'veg',
    image: 'https://images.unsplash.com/photo-1556157408-ed905925a4cd?w=600&auto=format&fit=crop',
  },
  {
    id: 'kalakand',
    name: 'Kalakand',
    description: 'Grainy milk-fudge squares topped with chopped pistachios.',
    category: 'Milk Sweets',
    price: 350,
    dietType: 'veg',
    image: 'https://media.istockphoto.com/id/1315042362/photo/indian-mithai-hot-kalakand-burfi-also-known-as-alwar-mawa-qalaqand-barfi-mishri-mava-or-khoa.webp?a=1&b=1&s=612x612&w=0&k=20&c=0uDrXGsPIj1A-YFd3OXLMHgjqStsk41O-DUEUurKJ8k=',
  },
  {
    id: 'rasmalai',
    name: 'Rasmalai',
    description: 'Flattened chenna dumplings in chilled saffron-cardamom milk.',
    category: 'Milk Sweets',
    price: 200,
    dietType: 'veg',
    image: 'https://media.istockphoto.com/id/515853026/photo/traditional-rasmalai-or-ras-malai-indian-dessert-bengali-sweet.webp?a=1&b=1&s=612x612&w=0&k=20&c=M_bkgtt4nYVBSvX5RrWxjG-y07gOvCyFH4x9aiQOVZo=',
  },
  {
    id: 'kesar-peda',
    name: 'Kesar Peda',
    description: 'Saffron-scented milk fudge discs, a festival favorite.',
    category: 'Milk Sweets',
    price: 300,
    dietType: 'veg',
    image: 'https://images.unsplash.com/photo-1672632426010-6fda4358bb6b?w=600&auto=format&fit=crop',
  },
  {
    id: 'mixed-namkeen',
    name: 'Mixed Namkeen',
    description: 'Savory gram-flour and lentil snack mix.',
    category: 'Savory',
    price: 220,
    dietType: 'veg',
    image: 'https://media.istockphoto.com/id/1295827560/photo/mix-namkeen.jpg?s=2048x2048&w=is&k=20&c=7RjCe9_O_6DprnN3a8k1LPtGpPROdYLwP4hdEDaWTiE=',
  },
  {
      id: 'pani-puri',
      name: 'Pani Puri',
      description: 'A popular street food, consisting of a round, hollow puri filled with a mixture of flavored water, tamarind chutney, chili, chaat masala, potato, onion, and chickpeas.',
      category: 'Chaats',
      price: 100,
      dietType: 'veg',
      image: 'https://b.zmtcdn.com/data/dish_photos/fcc/162fcd85aa376e19785986f623971fcc.jpeg?q=80&w=600&auto=format&fit=crop',
    },
  {
    id: 'samosa',
    name: 'Samosa',
    description: 'Crisp pastry filled with spiced potatoes and peas.',
    category: 'Savory',
    price: 40,
    dietType: 'veg',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop',
  },
  {
    id: 'sweet-box-assorted',
    name: 'Assorted Sweet Box',
    description: "A curated box of the shop's bestsellers, great for gifting.",
    category: 'Gift Boxes',
    price: 650,
    dietType: 'veg',
    image: 'https://images.unsplash.com/photo-1571823915295-c450f2c3f27a?w=600&auto=format&fit=crop',
  },
 
  ],
  'bishram-cafe': [
    {
      id: 'cappuccino',
      name: 'Cappuccino',
      description: 'Double espresso, steamed milk, thick foam.',
      category: 'Coffee',
      price: 180,
      dietType: 'veg',
      image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?q=80&w=600&auto=format&fit=crop',
    },
    {
    id: 's-momo',
    name: 'Steam Momo (Chicken)',
    description: 'Handmade dumplings stuffed with spiced minced chicken, steamed and served with tomato achar.',
    category: 'Momo',
    dietType: 'non-veg',
    price: 260,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's-momo2',
    name: 'Steam Momo (Veg)',
    description: 'Dumplings filled with finely chopped cabbage, carrot, and paneer, served with sesame-tomato chutney.',
    category: 'Momo',
    dietType: 'veg',
    price: 220,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'j-momo',
    name: 'Jhol Momo',
    description: 'Steamed momos served in a tangy, spiced sesame-tomato broth.',
    category: 'Momo',
    dietType: 'both',
    price: 280,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'k-momo',
    name: 'Kothey Momo',
    description: 'Pan-fried and steamed momos with a crisp base, served with spicy chutney.',
    category: 'Momo',
    dietType: 'non-veg',
    price: 270,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'nc-09',
    name: 'Dal Bhat Set',
    description: 'A wholesome plate of steamed rice, lentil soup, seasonal vegetable curry, pickle, and papad.',
    category: 'Mains',
    dietType: 'veg',
    price: 380,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'nc-10',
    name: 'Thakali Chicken Set',
    description: 'Rice, chicken curry, lentils, seasonal greens, pickle, and papad served on a traditional platter.',
    category: 'Mains',
    dietType: 'non-veg',
    price: 480,
    isVegetarian: false,
    image: 'https://media.istockphoto.com/id/2167582759/photo/nepali-meal-of-daal-bhaat-tarkari-thakali-thali-meat-rice-vegetables-and-pickle-dhido-meal.webp?a=1&b=1&s=612x612&w=0&k=20&c=vlnzqU92fJLjhwDkijNc-O4pXAoP3kAg0tC7JuSIhuQ=',
  },
  {
    id: 'nc-11',
    name: 'Choila',
    description: 'Spicy grilled and marinated buffalo or chicken, tossed with mustard oil, herbs, and spices — a Newari classic.',
    category: 'Newari Specials',
    dietType: 'non-veg',
    price: 350,
    image: 'https://images.unsplash.com/photo-1642821372719-46b426afd8b1?w=600&auto=format&fit=crop',
  },
  {
    id: 'nc-13',
    name: 'Sekuwa (Chicken)',
    description: 'Smoky skewered chicken marinated in Nepali spices, grilled over open flame.',
    category: 'Starters',
    dietType: 'non-veg',
    price: 340,
    image: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?q=80&w=600&auto=format&fit=crop',
  },
  
  ],
};

export function getMenuByRestaurantId(id) {
  return MENUS_BY_RESTAURANT[id] ?? [];
}