export const RESTAURANTS = [
  {
    id: 'sakura-ramen',
    name: 'Sakura Ramen House',
    description: 'Rich tonkotsu broth simmered 18 hours, hand-pulled noodles, and a killer chashu bowl.',
    cuisine: 'Japanese',
    address: 'Chabahil, Kathmandu',
    dietType: 'both',
    rating: 4.8,
    reviewCount: 320,
    priceLevel: 'Rs',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'taco-house',
    name: 'Tacos House',
    description: 'Street-style tacos, slow-roasted al pastor, and salsas made fresh every morning.',
    cuisine: 'Mexican',
    address: 'Kumaripati, Kathmandu',
    dietType: 'both',
    rating: 4.5,
    reviewCount: 214,
    priceLevel: 'Rs',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'green-basil',
    name: 'Green Basil Thai Kitchen',
    description: 'Fragrant curries, wok-fired noodles, and vegetarian options on every corner of the menu.',
    cuisine: 'Thai',
    dietType: 'both',
    address: 'Durbarmarg, Kathmandu',
    rating: 4.6,
    reviewCount: 178,
    priceLevel: 'Rs',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'the-square',
    name: 'The Square',
    description: 'Family-recipe pastas, wood-fired pizza, and a wine list picked by the owner himself.',
    cuisine: 'Italian',
    dietType: 'both',
    address: 'Patandhoka, Lalitpur',
    rating: 4.7,
    reviewCount: 402,
    priceLevel: 'Rs',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'daily-sushi',
    name: 'Daily Sushi',
    description: 'Authentic Sushi, authentic taste and a wine list picked by the owner himself.',
    cuisine: 'Chinese',
    dietType: 'non-veg',
    address: 'Patandhoka, Lalitpur',
    rating: 4.8,
    reviewCount: 204,
    priceLevel: 'Rs',
    image: 'https://b.zmtcdn.com/data/pictures/6/20583196/d538d11cd05d443edac17955bb3fdaae.jpg?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'angan-sweets',
    name: 'Angan Sweets',
    description: 'Traditional sweets crafted with love and authenticity.',
    cuisine: 'Sweets',
    address: 'Chakrapath, Kathmandu',
    dietType: 'veg',
    rating: 5,
    reviewCount: 9000,
    priceLevel: 'Rs',
    image: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'bishram-cafe',
    name: 'Bishram Cafe',
    description: 'Your cozy neighborhood corner for specialty coffee, freshly baked pastries, and a warm, welcoming atmosphere.',
    cuisine: 'Nepali',
    address: 'Chabahil, Kathmandu',
    dietType: 'both',
    rating: 4.2,
    reviewCount: 404,
    priceLevel: 'Rs',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=600&auto=format&fit=crop',
  },
];

export function getAllRestaurants() {
  return RESTAURANTS;
}

export function getRestaurantById(id) {
  return RESTAURANTS.find((restaurant) => restaurant.id === id) ?? null;
}